### ISSUE TITLE
Redeploy Weebo3

### ISSUE THREAD

**Issue by batleforc** [batleforc/WeeboGitOps#66]
En upgradant Tekton, le cluster à décider de ne plus fonctionner, donc il est nécessaire de faire une réinstallation dites "au propre".

- [x] Upgrade K3S pour que l'installation sois en 1.27.X #61 
- [x] Passage du cluster en IPV6 #63 
- [ ] Sécurisation de Harbor (Passage de tout les cache en privé, stockage des helm chart sur harbor, etc) #55
 - [x] Mise en place CSI #50
 - [x] Mise en place d'une vraie stack réseau + CNI #58 
 - [ ] Mise en place PodAutoScaller #17 
 - [x] Mise en place SealedSecrets #15 
 - [x] #67
 - [x] Setup Oauth2Proxy pour protéger le dashboard Longhorn  https://longhorn.io/docs/1.5.1/deploy/accessing-the-ui/longhorn-ingress/
 - [x] Setup Monitoring for Longhorn https://longhorn.io/docs/1.5.1/monitoring/prometheus-and-grafana-setup/

**Comment by batleforc** [comment]
- [x] layer 1 : CSI & & CNI & Namespace & & service mesh & & helmSource
- [x] layer 2 :  Dns, Cert Manager, Ingress
- [x] layer 3 : harbor, zitadel, mobitoring & co
- [x] layer 4 : gitea, gotify, microbin, sonarqube, minio 
- [x] layer 5 : adguard home, wireguard
- [x] layer 6 : buildkit, renovate, tekton
- [x] layer 7 : dashy, kavita, quake
- [x] layer 8 : buildall, portfolio, template

**Comment by batleforc** [comment]
```mermaid
flowchart TB
    subgraph Layer1
        CSI
        CNI
        Namespace
        ServiceMesh-REPORTED
        HelmSource
    end
    subgraph Layer2
        DNS
        CertManager
        HaProxyIngress
    end
    subgraph Layer3
        Secret
    end
    subgraph Layer4
        Harbor
        Zitadel
        Monitoring&Co
    end
    subgraph Layer5
        Gitea
        Gotify
        Microbin
        Sonarqube
        Minio
    end
    subgraph Layer6
        AdguardHome
        Wireguard
    end
    subgraph Layer7
        Buildkit
        Renovate
        Tekton
    end
    subgraph Layer8
        Dashy
        Kavita
        Quake
    end 
    subgraph Layer9
        BuildAll
        Portfolio
        Template
    end
    Layer1 --> Layer2
    Layer2 --> Layer3
    Layer3 --> Layer4
    Layer4 --> Layer5
    Layer7 --> Layer6
    Layer4 --> Layer7
    Layer4 --> Layer8
    Layer7 --> Layer9
```

**Comment by batleforc** [comment]
Travaille important effectuer sur la signature SOPS avec les TaskFile +age

**Comment by batleforc** [comment]
Layer 1 - 2 Ok
Layer 3 inited
